### ISSUE TITLE
Error in byte swapping

### ISSUE THREAD

**Issue by plstonge** [Aftersol/QOI-Codec#1]
Hi,

While checking your code, I have found that [sQOI.h#L198](https://github.com/Aftersol/Simplified-QOI-Codec/blob/main/inc/sQOI.h#L198) is shifting `value` twice with `>> 24`:
```
((value >> 24) & 0xFF | (value << 8) & 0xFF0000 | (value >> 8) & 0xFF00 | (value >> 24) & 0xFF000000);
```
The last bit shifting should be `<< 24` instead. Finally, for clarity reasons, it would be great if the 2nd and 3rd expressions between `|` were swapped. This would be like the following:
```
((value >> 24) & 0xFF | (value >> 8) & 0xFF00 | (value << 8) & 0xFF0000 | (value << 24) & 0xFF000000);
```

**Comment by N-R-K** [comment]
The proper fix would've been to not do any byte swapping at all. All that needs to happen is to shift the bytes into their proper place:

```c
uint32_t read32_be(uint8_t *p)
{
    return (uint32_t)p[0] << 24 | p[1] << 16 | p[2] << 8 | p[3];
}
```

This will work everywhere, without doing any system endian detection or byte swap. It also will work regardless of the alignment of `p` and doesn't suffer from any strict-aliasing violation. And modern compilers are [smart enough](https://godbolt.org/z/7YTscx9Wf) to optimize it properly.

The reference QOI decoder uses the [same technique](https://github.com/phoboslab/qoi/blob/c6219a56963baba831f05ce1f54ebe2208c0089d/qoi.h#L349-L353).

Further reading: ["The byte order fallacy"](https://commandcenter.blogspot.com/2012/04/byte-order-fallacy.html).
(Note: there's a small UB in that article, the 24 place shift needs to be casted to `uint32_t` to avoid overflowing INT_MAX).
